apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-0fyb
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0053-tenant/ci1t-830-0053-app/devfile-sample-0fyb@sha256:a23b999a50cd7c542a7befc778c4c8a0242168a36d197faa328d0910b96c0e82
        name: my-nodejs
        resources: {}
status: {}
